name: Smartstore Crawler

on:
  schedule:
    - cron: "0 * * * *"   # 매 정각마다 실행 (1시간마다)
  workflow_dispatch:       # 수동 실행 가능

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium gspread oauth2client requests beautifulsoup4

      - name: Run crawler script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python interest_to_sheet.py
